language: node_js
node_js:
  - v6
script:
  - yarn run lint && yarn test -- --coverage
cache:
  - yarn
before_deploy:
  - yarn run build

deploy:
  provider: firebase
  token:
    secure: ${FIREBASE_API_TOKEN}
